[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.13"

[features]
seeds = false
skip-lint = false

[programs.localnet]
defi_agent = "8reNvTG6PLT4sf4nGbT7VjZ1YqEGXzASkjcSQmQTkJPT"

[programs.devnet]
defi_agent = "8reNvTG6PLT4sf4nGbT7VjZ1YqEGXzASkjcSQmQTkJPT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
